version: "3"
services:
  app:
    image: johan3118/rate_app:latest
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    env_file:
      - .env
  database:
    image: johan3118/database_rate:latest
    volumes:
      - ./src:/app/src
    env_file:
      - .env
